name: WerewolfPlugin
version: 1.0
main: hoeve.plugins.werewolf.WerewolfPlugin
authors:
   - wbbraam
   - DeStilleGast

description: The Werewolves of Millers Hollow in Minecraft
api-version: 1.15

commands:
   werewolf:
      aliases:
         - ww
      description: Play werewolf on your server
      usage: /werewolf
